<a href="https://colab.research.google.com/github/agie-nugroho/shopping-cart-data-wrangling/blob/main/Shopping_Cart_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANALISIS DATA SHOPPING CART

1. Tahap Persiapan
2. Tahap Gathering Data
3. Tahap Assessing Data
4. Tahap Cleaning Data

In [2]:
# Gathering Data

# import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# koneksi ke Google Drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [3]:
# membuat file path

file_costumers = "/content/drive/MyDrive/data analyst/Data Wrangling/customers.csv"
file_orders = "/content/drive/MyDrive/data analyst/Data Wrangling/orders.csv"
file_products = "/content/drive/MyDrive/data analyst/Data Wrangling/products.csv"
file_sales = "/content/drive/MyDrive/data analyst/Data Wrangling/sales.csv"

customers_df = pd.read_csv(file_costumers)
orders_df = pd.read_csv(file_orders)
products_df = pd.read_csv(file_products)
sales_df = pd.read_csv(file_sales)

In [4]:
print(customers_df.head())
print(orders_df.head())
print(products_df.head())
print(sales_df.head())

   customer_id customer_name  gender  age                    home_address  \
0            1        Nama 1  Female   30  8606 Victoria TerraceSuite 560
1            2        Nama 2  Female   69      8327 Kirlin SummitApt. 461
2            3        Nama 3  Female   59       269 Gemma SummitSuite 109
3            4        Nama 4  Female   67       743 Bailey GroveSuite 141
4            5        Nama 5  Female   30         48 Hyatt ManorSuite 375

   zip_code               city                         state    country
0      5464      Johnstonhaven            Northern Territory  Australia
1      8223    New Zacharyfort               South Australia  Australia
2      5661           Aliburgh  Australian Capital Territory  Australia
3      1729  South Justinhaven                    Queensland  Australia
4      4032     Griffithsshire                    Queensland  Australia
   order_id  customer_id  payment order_date delivery_date
0         1           64    30811  2021-8-30    2021-09-24
1         2          473    50490   2021-2-3    2021-02-13
2         3          774    46763  2021-10-8    2021-11-03
3         4          433    39782   2021-5-6    2021-05-19
4         5          441    14719  2021-3-23    2021-03-24
   product_id product_type  product_name size colour  price  quantity  \
0           0        Shirt  Oxford Cloth   XS    red    114        66
1           1        Shirt  Oxford Cloth    S    red    114        53
2           2        Shirt  Oxford Cloth    M    red    114        54
3           3        Shirt  Oxford Cloth    L    red    114        69
4           4        Shirt  Oxford Cloth   XL    red    114        47

                                    description
0  A red coloured, XS sized, Oxford Cloth Shirt
1   A red coloured, S sized, Oxford Cloth Shirt
2   A red coloured, M sized, Oxford Cloth Shirt
3   A red coloured, L sized, Oxford Cloth Shirt
4  A red coloured, XL sized, Oxford Cloth Shirt
   sales_id  order_id  product_id  price_per_unit  quantity  total_price
0         0         1         218             106         2        212.0
1         1         1         481             118         1        118.0
2         2         1           2              96         3        288.0
3         3         1        1002             106         2        212.0
4         4         1         691             113         3        339.0

# ASSESSING DATA (MENILAI)

# DATA CUSTOMER

In [5]:
customers_df.info()
# menghitung jumlah missing values
customers_df.isna().sum()
customers_df["gender"]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1007 non-null   int64
 1   customer_name  1007 non-null   object
 2   gender         989 non-null    object
 3   age            1007 non-null   int64
 4   home_address   1007 non-null   object
 5   zip_code       1007 non-null   int64
 6   city           1007 non-null   object
 7   state          1007 non-null   object
 8   country        1007 non-null   object
dtypes: int64(3), object(6)
memory usage: 70.9+ KB

0                  Female
1                  Female
2                  Female
3                  Female
4                  Female
              ...
1002    Prefer not to say
1003    Prefer not to say
1004    Prefer not to say
1005    Prefer not to say
1006                 Male
Name: gender, Length: 1007, dtype: object

In [6]:
# mengecek jumlah duplikasi data berdasarkan customer_id
duplicate_ids = customers_df.duplicated(subset = ["customer_id"])
print(customers_df[duplicate_ids])
print("jumlah duplikasi:", duplicate_ids.sum())

     customer_id customer_name  gender  age                    home_address  \
317          304      Nama 318  Female   79        5306 Hickle MewsApt. 405
551          497      Nama 552    Male   31    0487 Jordan TerraceSuite 509
712          637      Nama 713    Male   58        8007 Joel SquareApt. 874
781          742      Nama 782    Male   44  275 Maddison Estate DrApt. 642
856          808      Nama 857    Male   35       4277 Ryan IslandSuite 792
907          808      Nama 908    Male   35       4277 Ryan IslandSuite 792
949          943      Nama 950    Male   64      3117 Heller PlaceSuite 149

     zip_code             city               state    country
317      7906      Feeneymouth          Queensland  Australia
551      9290  North Aidentown  Northern Territory  Australia
712      7700         Lilystad   Western Australia  Australia
781      8642     Port Aliview   Western Australia  Australia
856      4197      Robertstown   Western Australia  Australia
907      4197      Robertstown   Western Australia  Australia
949       822     North Elijah     South Australia  Australia
jumlah duplikasi: 7

In [7]:
# menampilkan statistika deskriptive
customers_df.describe()

       customer_id          age     zip_code
count  1007.000000  1007.000000  1007.000000
mean    501.726912    50.929494  5012.538232
std     288.673238    30.516299  2885.836112
min       1.000000    20.000000     2.000000
25%     252.500000    34.000000  2403.500000
50%     502.000000    50.000000  5087.000000
75%     751.500000    65.000000  7493.500000
max    1000.000000   700.000000  9998.000000

* Keterangan:

`age` -> terdapat outlier dengan umur max = 700

`customer_id` -> terurut -> distribusi normal

# DATA ORDER

In [8]:
# melihat ringkasan informasi data
# melihat missing value
# melihat jumlah baris dan kolom, tipe data dll
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   object
 4   delivery_date  1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

* `order_date` dan `delivery_date` masih bertipe `object`, dikonversikan ke `datetime`

In [9]:
# mengecek duplikasi data orders berdasarkan order_id
duplicate_id = orders_df.duplicated(subset = ["order_id"]).sum()
print("Jumlah duplikasi berdasarkan order_id:", duplicate_id)

Jumlah duplikasi berdasarkan order_id: 0

In [10]:
# menampilkan statistik deskriptif untuk data orders
orders_df.describe()

          order_id  customer_id       payment
count  1000.000000  1000.000000   1000.000000
mean    500.500000   506.640000  33972.936000
std     288.819436   277.115502  14451.609047
min       1.000000     1.000000  10043.000000
25%     250.750000   275.250000  21329.250000
50%     500.500000   515.000000  33697.500000
75%     750.250000   737.250000  46249.000000
max    1000.000000  1000.000000  59910.000000

# DATA PRODUCT

In [11]:
# melihat ringkasan data productt
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1266 entries, 0 to 1265
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1266 non-null   int64
 1   product_type  1266 non-null   object
 2   product_name  1266 non-null   object
 3   size          1266 non-null   object
 4   colour        1266 non-null   object
 5   price         1266 non-null   int64
 6   quantity      1266 non-null   int64
 7   description   1266 non-null   object
dtypes: int64(3), object(5)
memory usage: 79.3+ KB

In [12]:
# menampilkan data duplicate berdasarkan product_id
product_duplicate = products_df.duplicated(subset=["product_id"]).sum()
print("Jumlah data duplicate pada product adalah:", product_duplicate)
print(products_df[products_df.duplicated(subset=["product_id"])])

Jumlah data duplicate pada product adalah: 6
     product_id product_type product_name size  colour  price  quantity  \
112          54        Shirt        Dress   XL   green    119        52
232         146        Shirt        Linen    S  orange    116        42
365         146        Shirt        Linen    S  orange    116        42
435         377        Shirt       Henley    M  indigo     92        70
540         483       Jacket       Puffer    L  indigo    110        61
587         579       Jacket       Bomber   XL   green     90        79

                                   description
112    A green coloured, XL sized, Dress Shirt
232    A orange coloured, S sized, Linen Shirt
365    A orange coloured, S sized, Linen Shirt
435   A indigo coloured, M sized, Henley Shirt
540  A indigo coloured, L sized, Puffer Jacket
587  A green coloured, XL sized, Bomber Jacket

Terdapat 6 data duplikat

In [13]:
# melihat statistik deskriptif product
products_df.describe()

        product_id        price     quantity
count  1266.000000  1266.000000  1266.000000
mean    627.926540   105.812006    60.138231
std     363.971586     9.715611    11.682791
min       0.000000    90.000000    40.000000
25%     313.250000    95.250000    50.000000
50%     626.500000   109.000000    60.000000
75%     942.750000   114.000000    70.000000
max    1259.000000   119.000000    80.000000

# DATA SALES

In [14]:
# melihat info data sales
sales_df.info()
sales_df.isna().sum()
# terdapat 19 data missing di total_price

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sales_id        5000 non-null   int64
 1   order_id        5000 non-null   int64
 2   product_id      5000 non-null   int64
 3   price_per_unit  5000 non-null   int64
 4   quantity        5000 non-null   int64
 5   total_price     4981 non-null   float64
dtypes: float64(1), int64(5)
memory usage: 234.5 KB

sales_id           0
order_id           0
product_id         0
price_per_unit     0
quantity           0
total_price       19
dtype: int64

In [15]:
# melihat duplikasi data
sales_duplicated = sales_df.duplicated(subset=["sales_id", "order_id", "product_id"]).sum()
print("Jumlah duplikasi", sales_duplicated)

Jumlah duplikasi 0

In [16]:
# menampilkan statistik deksriptif data sales
sales_df.describe()

,sales_id,order_id,product_id,price_per_unit,quantity,total_price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,4981.000000
mean,2499.500000,503.038200,634.053200,103.501600,1.99240,206.307368
std,1443.520003,285.964418,363.255794,9.195004,0.80751,86.352449
min,0.000000,1.000000,1.000000,90.000000,1.00000,90.000000
25%,1249.750000,258.000000,323.000000,95.000000,1.00000,112.000000
50%,2499.500000,504.500000,635.000000,102.000000,2.00000,204.000000
75%,3749.250000,749.000000,951.000000,112.000000,3.00000,285.000000
max,4999.000000,999.000000,1259.000000,119.000000,3.00000,357.000000

# TAHAP CLEANING DATA

1. DATA CUSTOMERS

In [17]:
# menghapus duplikasi data
customers_df.drop_duplicates(subset=["customer_id"], inplace = True) # inplace langsung menerapkan di df asli
print("Jumlah duplikasi setelah cleaning: ", customers_df.duplicated(subset=["customer_id"]).sum())

customers_df.info()

Jumlah duplikasi setelah cleaning:  0
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 1006
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1000 non-null   int64
 1   customer_name  1000 non-null   object
 2   gender         982 non-null    object
 3   age            1000 non-null   int64
 4   home_address   1000 non-null   object
 5   zip_code       1000 non-null   int64
 6   city           1000 non-null   object
 7   state          1000 non-null   object
 8   country        1000 non-null   object
dtypes: int64(3), object(6)
memory usage: 78.1+ KB

In [18]:
# menangani missing value
print("\nBaris dengan missing value:\n", customers_df[customers_df.gender.isna()]) # melihat baris missing value

print("\nDistribusi gener sebelum diisi:\n", customers_df.gender.value_counts())  #melihat distribusi gender

# mengisi value kosong
customers_df.fillna(value="Prefer not to say", inplace=True)
print("\nJumlah missing value setelah filling:\n", customers_df.isna().sum())
customers_df["gender"].value_counts()

Baris dengan missing value:
      customer_id customer_name gender  age                     home_address  \
38            39       Nama 39    NaN   80  7440 Cameron Estate DrSuite 628
167          168      Nama 168    NaN   27         2781 Berge MallSuite 452
322          322      Nama 323    NaN   30        593 Becker CircleApt. 333
393          393      Nama 394    NaN   34          5158 Levi HillSuite 531
442          442      Nama 443    NaN   26           5157 Feil RoadApt. 633
722          720      Nama 723    NaN   40         31 Jordan ParadeApt. 400
745          743      Nama 746    NaN   57   09 Christopher StreetSuite 967
773          771      Nama 774    NaN   74     7367 Wright JunctionApt. 773
798          795      Nama 799    NaN   49          487 Summer MewsApt. 874
801          798      Nama 802    NaN   56           27 Aiden KnollApt. 875
825          822      Nama 826    NaN   59        41 Jenkins KnollSuite 438
859          855      Nama 860    NaN   55       603 O'keefe KnollSuite 782
863          859      Nama 864    NaN   38            32 Isla GroveApt. 078
914          909      Nama 915    NaN   62    976 Murray Station StApt. 036
934          929      Nama 935    NaN   68           394 Lily HillSuite 153
948          943      Nama 949    NaN   64       3117 Heller PlaceSuite 149
952          946      Nama 953    NaN   24      8227 Nicholas HillSuite 150
994          988      Nama 995    NaN   35   1130 Turner Estate DrSuite 925

     zip_code                   city                         state    country
38       4622  North Victoriachester            Northern Territory  Australia
167      1975         North Leoburgh             Western Australia  Australia
322      1640             Jacobiview             Western Australia  Australia
393      1474             Johnsburgh                    Queensland  Australia
442      7249             Port Chloe               New South Wales  Australia
722      1380             West Henry               South Australia  Australia
745      6226         Lake Lukemouth             Western Australia  Australia
773      8882               Kuhntown                      Victoria  Australia
798      1712            East Hayden  Australian Capital Territory  Australia
801      6531               Port Sam  Australian Capital Territory  Australia
825      2588        Lake Andrewport               South Australia  Australia
859      8822        Port Dylanmouth                      Tasmania  Australia
863      7711            Rosechester               New South Wales  Australia
914      3227               Langfort                      Tasmania  Australia
934      2353             Beahanfurt            Northern Territory  Australia
948       822           North Elijah               South Australia  Australia
952       115           South Jasper                    Queensland  Australia
994      9386              New Harry             Western Australia  Australia

Distribusi gener sebelum diisi:
 gender
Female               514
Male                 437
Prefer not to say     31
Name: count, dtype: int64

Jumlah missing value setelah filling:
 customer_id      0
customer_name    0
gender           0
age              0
home_address     0
zip_code         0
city             0
state            0
country          0
dtype: int64

gender
Female               514
Male                 437
Prefer not to say     49
Name: count, dtype: int64

In [19]:
# menangani innacurate value / Outlier pada customer
print("\n baris dengan umur maksimum sebelum cleaning:\n", customers_df[customers_df.age == customers_df.age.max()])

# replace
# customers_df.replace(customers_df.age.max(), 70, inplace=True)
# customers_df.replace(customers_df.age.max(), 50, inplace=True)
customers_df["age"].max()

 baris dengan umur maksimum sebelum cleaning:
      customer_id customer_name             gender  age  \
967          961      Nama 968  Prefer not to say  700

                   home_address  zip_code        city            state  \
967  29 Farrell ParadeSuite 818      6528  New Joseph  South Australia

       country
967  Australia

700

In [20]:
# mengecek kembali statistik deskriptif
customers_df.describe()

       customer_id         age     zip_code
count  1000.000000  1000.00000  1000.000000
mean    500.500000    50.94000  5004.872000
std     288.819436    30.59095  2884.497332
min       1.000000    20.00000     2.000000
25%     250.750000    34.00000  2401.750000
50%     500.500000    50.00000  5083.000000
75%     750.250000    65.00000  7460.250000
max    1000.000000   700.00000  9998.000000

2. DATA ORDER

In [21]:
# mengubah tipe tanggal menjadi datetime
datetime_columns = ["order_date", "delivery_date"]
print(orders_df[datetime_columns])

for column in datetime_columns:
  orders_df[column] = pd.to_datetime(orders_df[column])

orders_df.info()

    order_date delivery_date
0    2021-8-30    2021-09-24
1     2021-2-3    2021-02-13
2    2021-10-8    2021-11-03
3     2021-5-6    2021-05-19
4    2021-3-23    2021-03-24
..         ...           ...
995  2021-1-13    2021-02-02
996  2021-1-18    2021-01-31
997   2021-5-5    2021-05-21
998  2021-6-15    2021-07-12
999   2021-4-7    2021-04-24

[1000 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   datetime64[ns]
 4   delivery_date  1000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3)
memory usage: 39.2 KB

3. DATA PRODUCT

In [22]:
# menghapus data yang duplikat
products_df.drop_duplicates(subset=["product_id"], inplace=True)  # menghapus baris duplikat berdasarkan product_id

# mengecek kembali jumlah data duplikat setelah pembersihan
print("Jumlah duplikasi:", products_df.duplicated(subset=["product_id"]).sum())

Jumlah duplikasi: 0

4. DATA SALES

In [34]:
# menampilkan data dengan nilai NaN pada kolom total_price
sales_df[sales_df.total_price.isna()]

# mengisi nilai yang NaN dengan perhitungan ppu * quantity
sales_df["total_price"] = sales_df["price_per_unit"] * sales_df["quantity"]

sales_df["total_price"]

0       212
1       118
2       288
3       212
4       339
       ...
4995    218
4996    285
4997    113
4998    212
4999    115
Name: total_price, Length: 5000, dtype: int64

# MENYIMPAN DATA YANG TELAH DIBERSIHKAN KE FILE CSV

In [36]:
# membuat folder output
import os
output_path = "/content/drive/MyDrive/data analyst/Data Wrangling"
os.makedirs(output_path, exist_ok=True)

# simpan setiap dataset yang sudah dibersihkan
customers_df.to_excel(f"{output_path}/costumers_cleaned.xlsx", index=False)
orders_df.to_excel(f"{output_path}/orders_cleaned.xlsx", index=False)
products_df.to_excel(f"{output_path}/products_cleaned.xlsx", index=False)
sales_df.to_excel(f"{output_path}/sales_cleaned.xlsx", index=False)

print("Semua data berhasil disimpan ke folder:")
print(output_path)

Semua data berhasil disimpan ke folder:
/content/drive/MyDrive/data analyst/Data Wrangling

🔹 Penjelasan Kode

* `os.makedirs(path, exist_ok=True)` → membuat folder baru; `exist_ok=True` mencegah error jika folder sudah ada.

* `to_csv(..., index=False)` → menyimpan DataFrame ke file CSV tanpa kolom indeks agar lebih rapi.

* Folder output dipisahkan agar file bersih mudah ditemukan dan dikelola.

* `print(output_path)` → menampilkan path folder hasil simpan, memudahkan navigasi di Google Drive/Colab.

# JOIN DALAM PYTHON

In [44]:
# INNER JOIN (hanya mengambil yang beririsan di kedua tabel)
inner_join_df = pd.merge(customers_df, orders_df, on="customer_id", how="inner")
print("Inner Join:\n",inner_join_df.head())

# LEFT JOIN (hanya mengambil semua data dari tabel kiri dan irisan dari kedua tabel)
left_join_df = pd.merge(customers_df, orders_df, on="customer_id", how="left")
print("\nLeft Join:\n", left_join_df)

# RIGHT JOIN (hanya mengambil semua dari dari tabel kanan dan irisan dari kedua tabel)
right_join_df = pd.merge(customers_df, orders_df, on="customer_id", how="right")
print("\nRight Join:\n", right_join_df)

# OUTER JOIN (mengambil semua kemungkinan dari kedua tabel, gabungkan jika cocok)
outer_join_df = pd.merge(customers_df, orders_df, on="customer_id", how="outer")
print("\nOuter Join:\n", outer_join_df)

Inner Join:
    customer_id customer_name  gender  age                    home_address  \
0            1        Nama 1  Female   30  8606 Victoria TerraceSuite 560
1            1        Nama 1  Female   30  8606 Victoria TerraceSuite 560
2            1        Nama 1  Female   30  8606 Victoria TerraceSuite 560
3            7        Nama 7  Female   76     92 Hills Station StApt. 683
4           10       Nama 10  Female   70       615 Hayley KnollSuite 454

   zip_code           city               state    country  order_id  payment  \
0      5464  Johnstonhaven  Northern Territory  Australia       455    24550
1      5464  Johnstonhaven  Northern Territory  Australia       670    10246
2      5464  Johnstonhaven  Northern Territory  Australia       729    35593
3       793      Masonfurt          Queensland  Australia       465    48935
4      2118      Joelburgh   Western Australia  Australia       595    45626

  order_date delivery_date
0 2021-04-04    2021-04-06
1 2021-03-06    2021-04-01
2 2021-02-18    2021-03-01
3 2021-05-21    2021-05-23
4 2021-03-09    2021-03-29

Left Join:
       customer_id customer_name             gender  age  \
0               1        Nama 1             Female   30
1               1        Nama 1             Female   30
2               1        Nama 1             Female   30
3               2        Nama 2             Female   69
4               3        Nama 3             Female   59
...           ...           ...                ...  ...
1378          998     Nama 1005  Prefer not to say   32
1379          998     Nama 1005  Prefer not to say   32
1380          998     Nama 1005  Prefer not to say   32
1381          999     Nama 1006  Prefer not to say   30
1382         1000     Nama 1007               Male   71

                        home_address  zip_code                city  \
0     8606 Victoria TerraceSuite 560      5464       Johnstonhaven
1     8606 Victoria TerraceSuite 560      5464       Johnstonhaven
2     8606 Victoria TerraceSuite 560      5464       Johnstonhaven
3         8327 Kirlin SummitApt. 461      8223     New Zacharyfort
4          269 Gemma SummitSuite 109      5661            Aliburgh
...                              ...       ...                 ...
1378       72 Annabelle PassApt. 446        52          Kohlerberg
1379       72 Annabelle PassApt. 446        52          Kohlerberg
1380       72 Annabelle PassApt. 446        52          Kohlerberg
1381       170 Wilson AvenueApt. 577      7849      East Oscarfurt
1382      1671 Lauren KnollSuite 945      9012  Lake Audreyborough

                             state    country  order_id  payment order_date  \
0               Northern Territory  Australia     455.0  24550.0 2021-04-04
1               Northern Territory  Australia     670.0  10246.0 2021-03-06
2               Northern Territory  Australia     729.0  35593.0 2021-02-18
3                  South Australia  Australia       NaN      NaN        NaT
4     Australian Capital Territory  Australia       NaN      NaN        NaT
...                            ...        ...       ...      ...        ...
1378                    Queensland  Australia     404.0  45215.0 2021-03-03
1379                    Queensland  Australia     586.0  15870.0 2021-02-27
1380                    Queensland  Australia     773.0  21349.0 2021-07-19
1381             Western Australia  Australia       NaN      NaN        NaT
1382                      Tasmania  Australia     894.0  35622.0 2021-10-11

     delivery_date
0       2021-04-06
1       2021-04-01
2       2021-03-01
3              NaT
4              NaT
...            ...
1378    2021-03-09
1379    2021-03-22
1380    2021-08-07
1381           NaT
1382    2021-10-13

[1383 rows x 13 columns]

Right Join:
      customer_id customer_name  gender  age                   home_address  \
0             64       Nama 64  Female   75      4927 Alice MeadowApt. 960
1            473      Nama 474    Male   61  531 Schmitt BoulevardApt. 010
2            774      Nama 777    Male   34       2096 Wilson MewsApt. 714
3            433      Nama 434  Female   46        5777 Mayer PassApt. 881
4            441      Nama 442  Female   53   33 Richards JunctionApt. 478
..           ...           ...     ...  ...                            ...
995          345      Nama 346  Female   62      9182 Hermann MallApt. 890
996          346      Nama 347  Female   40    59 Bergstrom GroveSuite 260
997          407      Nama 408    Male   41      5233 Lara AvenueSuite 291
998          428      Nama 429  Female   66      80 Hermiston WaySuite 403
999          896      Nama 901    Male   67     985 Nguyen TerraceApt. 362

     zip_code                city                         state    country  \
0        7787      Sanfordborough               South Australia  Australia
1        1744             Annaton               South Australia  Australia
2        8590  West Jonathanshire                      Tasmania  Australia
3        9728    West Michaelport                      Tasmania  Australia
4        7650     South Rileyview             Western Australia  Australia
..        ...                 ...                           ...        ...
995       799          Audreyfurt                      Victoria  Australia
996      6060           Olsonbury            Northern Territory  Australia
997      8697       Hartmannshire                    Queensland  Australia
998      1112      North Liamfort  Australian Capital Territory  Australia
999      7737            Ryanberg               South Australia  Australia

     order_id  payment order_date delivery_date
0           1    30811 2021-08-30    2021-09-24
1           2    50490 2021-02-03    2021-02-13
2           3    46763 2021-10-08    2021-11-03
3           4    39782 2021-05-06    2021-05-19
4           5    14719 2021-03-23    2021-03-24
..        ...      ...        ...           ...
995       996    37843 2021-01-13    2021-02-02
996       997    53831 2021-01-18    2021-01-31
997       998    53308 2021-05-05    2021-05-21
998       999    31643 2021-06-15    2021-07-12
999      1000    27836 2021-04-07    2021-04-24

[1000 rows x 13 columns]

Outer Join:
       customer_id customer_name             gender  age  \
0               1        Nama 1             Female   30
1               1        Nama 1             Female   30
2               1        Nama 1             Female   30
3               2        Nama 2             Female   69
4               3        Nama 3             Female   59
...           ...           ...                ...  ...
1378          998     Nama 1005  Prefer not to say   32
1379          998     Nama 1005  Prefer not to say   32
1380          998     Nama 1005  Prefer not to say   32
1381          999     Nama 1006  Prefer not to say   30
1382         1000     Nama 1007               Male   71

                        home_address  zip_code                city  \
0     8606 Victoria TerraceSuite 560      5464       Johnstonhaven
1     8606 Victoria TerraceSuite 560      5464       Johnstonhaven
2     8606 Victoria TerraceSuite 560      5464       Johnstonhaven
3         8327 Kirlin SummitApt. 461      8223     New Zacharyfort
4          269 Gemma SummitSuite 109      5661            Aliburgh
...                              ...       ...                 ...
1378       72 Annabelle PassApt. 446        52          Kohlerberg
1379       72 Annabelle PassApt. 446        52          Kohlerberg
1380       72 Annabelle PassApt. 446        52          Kohlerberg
1381       170 Wilson AvenueApt. 577      7849      East Oscarfurt
1382      1671 Lauren KnollSuite 945      9012  Lake Audreyborough

                             state    country  order_id  payment order_date  \
0               Northern Territory  Australia     455.0  24550.0 2021-04-04
1               Northern Territory  Australia     670.0  10246.0 2021-03-06
2               Northern Territory  Australia     729.0  35593.0 2021-02-18
3                  South Australia  Australia       NaN      NaN        NaT
4     Australian Capital Territory  Australia       NaN      NaN        NaT
...                            ...        ...       ...      ...        ...
1378                    Queensland  Australia     404.0  45215.0 2021-03-03
1379                    Queensland  Australia     586.0  15870.0 2021-02-27
1380                    Queensland  Australia     773.0  21349.0 2021-07-19
1381             Western Australia  Australia       NaN      NaN        NaT
1382                      Tasmania  Australia     894.0  35622.0 2021-10-11

     delivery_date
0       2021-04-06
1       2021-04-01
2       2021-03-01
3              NaT
4              NaT
...            ...
1378    2021-03-09
1379    2021-03-22
1380    2021-08-07
1381           NaT
1382    2021-10-13

[1383 rows x 13 columns]

🔹 Penjelasan Metode Join

on="customer_id" → kolom yang digunakan untuk menggabungkan kedua DataFrame.

how parameter:

"inner" → hanya baris yang cocok di kedua DataFrame.

"left" → semua baris dari DataFrame kiri (customers_df) + data cocok dari kanan.

"right" → semua baris dari DataFrame kanan (orders_df) + data cocok dari kiri.

"outer" → semua baris dari kedua DataFrame, gabungkan jika ada kecocokan.